k0kubun/hamlit

lib/hamlit/compilers/old_attribute.rb
spec/rails/app/views/users/old_attributes.html.haml
spec/rails/spec/hamlit_spec.rb

```haml
%a{ data: { value: t('foo', count: 1) } }
%a{ data: { value: [count: 1] } }
```
```
in ~/Develop/creasty/hamlit on fix_attributes_parse_error *
❯ be hamlit parse tmp/in.haml
[:multi,
[:html,
:tag,
"a",
[:haml, :attrs, "{ data: { value: t('foo', count: 1) } }"],
[:multi]],
[:newline],
[:static, "\n"],
[:html,
:tag,
"a",
[:haml, :attrs, "{ data: { value: [count: 1] } }"],
[:multi]],
[:newline],
[:static, "\n"]]
in ~/Develop/creasty/hamlit on fix_attributes_parse_error *
❯ be hamlit compile tmp/in.haml
_buf = []; _buf << ("<a data-value='".freeze); _buf << (t('foo', count: 1); _buf << ("'></a>\n<a data-value='".freeze);
; _buf << ([count: 1); _buf << ("'></a>\n".freeze);
; _buf = _buf.join
in ~/Develop/creasty/hamlit on fix_attributes_parse_error *
❯ be hamlit render tmp/in.haml …
```

Fix reject_nested_columns to consider parentheses and brackets

---

README.md

This PR updates README.md. Just use set option to escape html in sinatra.

Update README.md (How to escape html in sinatra)

---

hamlit.gemspec
lib/hamlit/compiler.rb
lib/hamlit/compilers/dynamic.rb
lib/hamlit/engine.rb
lib/hamlit/temple.rb

- Add [escape_utils](https://github.com/brianmario/escape_utils) as dependency
- Reduce unnecessary `to_s` call

Use escape_utils for Temple::Utils.escape_html

---

lib/hamlit/compilers/new_attribute.rb
spec/hamlit/engine/new_attribute_spec.rb
spec/spec_helper.rb

I came across this when trying to use hamlit with angular. It currently parses all parts but the last of a hyphenated attribute as separate atomic attributes.

Allow hyphenated HTML-style attributes

---

CHANGELOG.md

I noticed that you have a comprehensive changelog so I decided to optimize it so that it can contain more information.
The first commit just adds dates to the versions and useful github compare links so that if one wants to find out more about the difference between this version and previous one simply needs to click on a version number. This commit is not as obtrusive and if you chose to accept it should not be much of a hassle for you to maintain it in that format.
The second commit fully introduces suggestions from [keep-a-changelog](https://github.com/olivierlacan/keep-a-changelog/) and modifies the body of each release to contain categories of change. This commit requires more effort to maintain, down the road so if you find that this is too much of a change to your work flow feel …

Changelog optimization

---

lib/hamlit/compiler/tag_compiler.rb

This fix following problem.
```
$ ruby -S -Ilib ./exe/hamlit temple benchmark/dynamic_attributes/boolean_attribute.haml
./lib/hamlit/compiler/tag_compiler.rb:64:in `self_closing?': undefined method `include?' for nil:NilClass (NoMethodError)
Did you mean?  @autoclose
from lib/hamlit/compiler/tag_compiler.rb:26:in `compile_contents'
from lib/hamlit/compiler/tag_compiler.rb:16:in `compile'
from lib/hamlit/compiler.rb:86:in `compile_tag'
from lib/hamlit/compiler.rb:49:in `compile'
from lib/hamlit/compiler.rb:58:in `block in compile_children'
from lib/hamlit/compiler/children_compiler.rb:16:in `block in compile'
from lib/hamlit/compiler/children_compiler.rb:13:in `each'
from lib/hamlit/compiler/children_compiler.rb:13:in `compile'
from lib/hamlit/compiler.rb:58:in `compile_children'
from …
```

fix error when autoclose option is nil

---

benchmark/ext/build_data.rb

benchmark/ext/build_data.rb
Both benchmark includes string allocation.
Faml::AttributeBuilder includes hash building.
(It maybe fair to include hash building for Faml::AttributeBuilder considering real world situation.)
But this benchmark's interest is pure speed between Faml::AttributeBuilder.build and Hamlit::AttributeBuilder.build_data. So it may be more acurate by removing that code.
BEFORE
```
Calculating -------------------------------------
Faml::AB.build    10.567k i/100ms
Hamlit.build_data    10.125k i/100ms
-------------------------------------------------
Faml::AB.build    165.685k i/s (0.006ms) -    834.793k
Hamlit.build_data    153.934k i/s (0.006ms) -    769.500k
Comparison:
Faml::AB.build:   165684.7 i/s (0.006ms)
Hamlit.build_data:   153933.8 i/s (0.006ms) - 1.08x slower …
```

make benchmark to more accurate.

---

hamlit.gemspec

Hamlit uses own Hamlit::Utils.escape_html, not
Temple::Utils.escape_html.

Remove escape_utils dependency

---

lib/hamlit/compiler/attribute_compiler.rb
test/hamlit/engine/attributes_test.rb

Fixing the issue:
```html
%div{ id: 60 }
<div id='<'>
```
In Temple, `value` of `[:static, value]` must be `String`. With `String#concat` in `Temple::Filters::StaticMerger`, `Fixnum`(`60`) is converted to `"<"` like `#chr`.

Fix rendering failure for static integer

---

CHANGELOG.md
lib/hamlit/attribute_compiler.rb
lib/hamlit/compiler/script_compiler.rb
lib/hamlit/compiler/tag_compiler.rb
lib/hamlit/engine.rb
lib/hamlit/string_splitter.rb
test/hamlit/optimization_test.rb
test/hamlit/string_splitter_test.rb

Refactoring with following changes.
`%input{ value: "foo#{ "bar#{ baz }" }" }` is optimized recursively

Extract StringSplitter to Temple filter 

---

README.md

Without cloning submodules `bundle install` will work fine but `bundle exec rake test` will exception. Took me a little while to realise what was going on:
```
$ bundle exec rake test
mkdir -p tmp/x86_64-darwin14/hamlit/2.2.3
cd tmp/x86_64-darwin14/hamlit/2.2.3
/Users/hfaulds/.rbenv/versions/2.2.3/bin/ruby -I. ../../../../ext/hamlit/extconf.rb
creating Makefile
cd -
cd tmp/x86_64-darwin14/hamlit/2.2.3
make
compiling ../../../../ext/hamlit/hamlit.c
../../../../ext/hamlit/hamlit.c:3:10: fatal error: 'houdini.h' file not found
#include "houdini.h"
^
1 error generated.
make: *** [hamlit.o] Error 1
rake aborted!
Command failed with status (2): [make...]
Tasks: TOP => test => compile => compile:x86_64-darwin14 => compile:hamlit:x86_64-darwin14 => copy:hamlit:x86_64-darwin14:2.2.3 => …
```

Update README.md to clone submodules

---

exe/hamlit

During the development of #60, I fund the bug that the loadpath inside of `exe/hamlit` is wrong.
Before this patch the installed gem is loaded inside the `exe` and not the working copy.

fix exe load path

---

.gitmodules
ext/hamlit/extconf.rb
ext/hamlit/hamlit.c
ext/hamlit/hescape.c
ext/hamlit/hescape.h
hamlit.gemspec

Drop houdini from dependency and stop using submodule. It'll release us from build issues on windows https://github.com/k0kubun/hamlit/issues/69 and packaging problems https://github.com/k0kubun/hamlit/issues/79. Since they are almost the same, it won't affect performance. Just for maintainability.

Rewrite HTML escape function

---

lib/hamlit/attribute_builder.rb

Tiny change, adds `download` for anchor tags, as [described in MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-download).

add `download` as BOOLEAN_ATTRIBUTE for anchors

---

lib/hamlit/cli.rb

In UNIX convention, `-` means STDIN, and it is sometimes useful, e.g. use in other toolchains via pipelines (`x foo.haml | preprocessor | hamlit compile -`).

make `hamlit compile -` to read things from stdin

---

lib/hamlit/filters/coffee.rb
lib/hamlit/filters/less.rb
lib/hamlit/filters/markdown.rb
lib/hamlit/filters/sass.rb
lib/hamlit/filters/scss.rb
lib/hamlit/filters/tilt_base.rb

I use Kramdown for markdown rendering.
When I upgraded to Tilt 2, Hamlit started trying to require redcarpet.
This change should make it so that redcarpet (And other engines) are only registered when Tilt doesn't already have another engine registered.

upgrading to Tilt 2 forces specific interpreter usage

---

lib/hamlit/rails_template.rb

When trying rails 6.0.0.beta3 with hamlit 2.9.2, I found a following deprecation warning:
```
DEPRECATION WARNING: Single arity template handlers are deprecated.  Template handlers must
now accept two parameters, the view object and the source for the view object.
Change:
>> Hamlit::RailsTemplate#call(template)
To:
>> Hamlit::RailsTemplate#call(template, source)
```
This pull request brings hamlit template handler up to work with Rails 6 and no deprecation warnings.
See also:
- https://github.com/rails/rails/pull/35119
- https://github.com/haml/haml/pull/1008
- https://github.com/rails/coffee-rails/pull/101
- https://github.com/rails/jbuilder/pull/453

Fix deprecation warning on Rails 6

---

.github/workflows/test.yml

Thanks for the gem!
All specs are passing locally on Ruby 3 (ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin19])
```
Finished in 4.189119s, 259.2431 runs/s, 277.8627 assertions/s.
1086 runs, 1164 assertions, 0 failures, 0 errors, 203 skips
```

adds Ruby 3.0 to CI

---

.github/workflows/test.yml
.gitignore

this should decrease build time for specs by caching installed dependencies
total CI run time without cache: ~ 2min (2.4x)
with cache:  ~ 50sec (1x)

Use GitHub action cache

---

lib/hamlit/cli.rb

IRB's syntax highlight is based on Ripper, so it gives a better result than Pry.

Use IRB for colorizing CLI

---

ext/hamlit/hamlit.c

Eliminate rb_const_get for static strings to workaround SEGV after GC.compact

---

REFERENCE.md
lib/hamlit/railtie.rb

In order not to have to `require 'hamlit/rails_template'`, make sure it is called beforehand.
<del>Minor documentation fix that I needed to use `RailsTemplate` in an initializer. (hamlit 2.14.2, hamlit-rails 0.2.3, rails 6.0, Ruby 2.5.7.)</del>

Ensure the initializer is called before the application's initializers

---

.github/workflows/bench.yml

Revert benchmark CI  jobs dropped on migration from Travis CI to GitHub Actions in #167.
1. `travis-ci.org` will be shut down in days https://blog.travis-ci.com/2021-05-07-orgshutdown, so we will be able to see the job shown in README: `https://travis-ci.org/github/k0kubun/hamlit/jobs/732178446`.
2. With hamlit 2.15.0, I sometimes saw some performance degradation with uncertain stability in my (unstable) environment (see below), so I will be happy to track the results continuously.
```
Comparison:
erubi v1.10.0:   221094.2 i/s
slim v4.1.0:   217911.3 i/s - 1.01x slower
hamlit v2.15.0:   181058.4 i/s - 1.22x slower
faml v0.8.1:   165955.5 i/s - 1.33x slower
haml v5.2.1:   130652.8 i/s - 1.69x slower
```
```
Comparison:
hamlit v2.15.0:   229626.8 i/s
erubi v1.10.0:   215138.1 i/s - 1.07x …
```

Add bench to GitHub Actions

---

hamlit.gemspec

This PR omits `benchmark/` directory from the published package. 
The directory is a bit of large, so this PR reduces network and disk usage.
It reduces 536,576 bytes, about 89%, from the tarball package, which is created by `rake build` command.
```bash
$ du pkg/* --summarize --bytes 
66560	pkg/hamlit-2.15.0.gem-after
603136	pkg/hamlit-2.15.0.gem-before
```

Omit benchmark/ directory from published package

---

lib/hamlit/cli.rb
lib/hamlit/engine.rb
lib/hamlit/parser.rb

( This Pull Request has been continued from https://github.com/k0kubun/hamlit/pull/188#issuecomment-1028590147 )
raise the error in `Hamlit::Parser` when `hamlit compile -c` to check haml error.
```
$ cat invalid-haml-syntax.haml
%h1
title
%div
%span
```
Before this Pull Request
```
$ bundle exec exe/hamlit compile -c invalid-haml-syntax.haml
Syntax OK
$ echo $?
0
```
After this Pull Request
```
$ bundle exec exe/hamlit compile -c invalid-haml-syntax.haml
bundler: failed to load command: exe/hamlit (exe/hamlit)
(haml):4: Inconsistent indentation: 1 space used for indentation, but the rest of the document was indented using 2 spaces. (Hamlit::HamlSyntaxError)
...
$ echo $?
1
```

Raise haml error when compile check

---

lib/hamlit/filters/tilt_base.rb

Fixes #195.
In sass-embedded, it is protobuf returning frozen string as result. While we could unfreeze it after we get the result in upstream libraries e.g. sass-embedd or tilt, it is intentionally left frozen for best performance. Therefore, this PR updates the code to conditionally use `.gsub` vs `.gsub!`. I did a benchmark locally and it is consistently at least around 5% faster than `(+text).gsub!` on my machine.

Support sass-embedded
